CREATE TABLE IF NOT EXISTS `pto` (
  `id_pto` INT(11) NOT NULL AUTO_INCREMENT,
  `id_pelanggan` INT(11) NOT NULL,
  `nm_pelanggan` VARCHAR(120) DEFAULT NULL,
  `jenis_kelamin` VARCHAR(30) DEFAULT NULL,
  `umur` VARCHAR(30) DEFAULT NULL,
  `alamat_pelanggan` TEXT,
  `tlp_pelanggan` VARCHAR(30) DEFAULT NULL,
  `tanggal_1` DATE DEFAULT NULL,
  `catatan_1` TEXT,
  `obat_1` TEXT,
  `masalah_1` TEXT,
  `tindak_1` TEXT,
  `tanggal_2` DATE DEFAULT NULL,
  `catatan_2` TEXT,
  `obat_2` TEXT,
  `masalah_2` TEXT,
  `tindak_2` TEXT,
  `tempat_ttd` VARCHAR(120) DEFAULT NULL,
  `tanggal_ttd` DATE DEFAULT NULL,
  `created_by` VARCHAR(120) DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_pto`),
  KEY `idx_pto_pelanggan` (`id_pelanggan`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;